# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UsDRdKWhTpUzYVsSwg5mEMjrWOeJYzzf
"""

g = 1234
h = []
while g >= 1:
  i = g / 10
  j = g // 10
  k = (i - j)
  h.append(round(k*10))
  g = j

h.reverse()

for l in h:
  m = l * h[1]
  n = h.pop()
  o = n * h[-1]
  p = m * o
  print(p)