# -*- coding: utf-8 -*-
"""Problemas de las N reynas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cHWLrOzqpVW3ql_jUx2G75SnoAMz-GV5
"""

def es_seguro(tablero, fila, columna):
    for i in range(fila):
        if tablero[i] == columna or tablero[i] - i == columna - fila or tablero[i] + i == columna + fila:
            return False
    return True

def solucionar_n_reinas(Reynas):
    tablero = [-1] * Reynas
    if solucionar_n_reinas_util(tablero, 0):
        for fila in range(Reynas):
            for columna in range(Reynas):
                if tablero[fila] == columna:
                    print("ඞ ", end="")
                else:
                    print(". ", end="")
            print()
    else:
        print("pailas pai")

def solucionar_n_reinas_util(tablero, fila):
    Reynas = len(tablero)
    if fila == Reynas:
        return True
    for columna in range(Reynas):
        if es_seguro(tablero, fila, columna):
            tablero[fila] = columna
            if solucionar_n_reinas_util(tablero, fila + 1):
                return True
            tablero[fila] = -1
    return False

solucionar_n_reinas(2)