# -*- coding: utf-8 -*-
"""Taller 5 - Houdini.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cq0hCyBfyG-wOTkEUfaEsCotTkABoWOr
"""

def contar_caminos(laberinto):
    filas = len(laberinto)
    columnas = len(laberinto[0])

    temp = [[0] * columnas for p in range(filas)]   #Creamos una matriz para ir almacenando los resultados

    for i in range(filas):          #Inicializamos la primera columna
        if laberinto[i][0] == -1:
            break
        temp[i][0] = 1

    for i in range(filas):        #Hacemos el calculo de los caminos para cada celda
        for j in range(1, columnas):
            if laberinto[i][j] != -1:
                if i > 0 and laberinto[i - 1][j] != -1:
                    temp[i][j] += temp[i - 1][j]
                if j > 0 and laberinto[i][j - 1] != -1:
                  
                    temp[i][j] += temp[i][j - 1]

    return temp[filas - 1][columnas - 1]    #Retornamos la cantidad de caminos para llegar a la posición más a la derecha

laberinto = [[0, 0, 0, 0, 0],
             [0, -1, 0, 0, 0],
             [-1, 0, 0, 0, 0],
             [0, 0, 0, 0, 0]]

resultado = contar_caminos(laberinto)
print("Te mide:", resultado,"cm")