# -*- coding: utf-8 -*-
"""Prueba para Proyecto.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1actE5DaasiEDafZDuX7rWVGaAoFjHNkn
"""

def min_operaciones(N):
  dp = [0] * (N+1)
  dp[1] = 1
  for i in range(0, N+1):
    if i % 2 == 0:
      dp[i] = dp[i//2] + 1
    else:
      dp[i] = dp[i-2] + 1
  return dp[N]

min_operaciones(8)

def emparejamiento(A,B):
  if len(A) == 0:
    return 0

  suma_diferencias = abs(A.pop(A.index(min(A))) - B.pop(B.index(min(B)))) + emparejamiento(A,B)
  return suma_diferencias

ZZZ = [4,1,8,7]
XXX = [2,3,6,5]

print(emparejamiento(ZZZ,XXX))